### ISSUE TITLE
Custom input test

### ISSUE THREAD

**Issue by NaveenGandla** [EagleW/Describing_a_Knowledge_Base#2]
Hello, 

Great repo on NLG. 
May I know how to test the trained model with custom input. 

Thanks

**Comment by EagleW** [comment]
@NaveenGandla , thank you for your interest in our research. A quick fix for this problem is change the test data with your customized input and use mode 1 to test it out. Feel free to ask my if you have another concerns.

**Comment by architlatkar27** [comment]
Hi, is it possible to give inputs from some other datasets? I tried giving rotowire as test file but it is not working. In fact after I trained the model for animals dataset, I was not able to get outputs for People dataset as well. Is there any fix around this? 

thanks in advance

**Comment by EagleW** [comment]
Hi @architlatkar27 , can you share your error information here? Thanks!

**Comment by architlatkar27** [comment]
![dakb_error](https://user-images.githubusercontent.com/52096846/126045568-0f89274a-4539-4408-9c97-265ca75dc508.png)


here i am using a copy of the test_wiki_P.json file renamed as test_wiki_A.json and then preprocessed. When i run the code for testing, it throws some error.
Thanks for looking into it

**Comment by EagleW** [comment]
I think that's because the vocabulary sets of person and animal are different. You should test your person data over person training sets.

**Comment by hoangthangta** [comment]
> 

I faced the same issue. Do you have any fix here?

**Comment by hoangthangta** [comment]
> ![dakb_error](https://user-images.githubusercontent.com/52096846/126045568-0f89274a-4539-4408-9c97-265ca75dc508.png)
> 
> here I am using a copy of the test_wiki_P.json file renamed as test_wiki_A.json and then preprocessed. When I run the code for testing, it throws some errors. Thanks for looking into it

I faced the same issue. Do you have any fixes here?

**Comment by EagleW** [comment]
Did you test your person data over person training sets?
