### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by yuanyuan12080317** [EagleW/Describing_a_Knowledge_Base#4]
首先十分感谢您的回复  python main.py --cuda --mode 3 报错BrokenPipeError: [Errno 32] Broken pipe
--mode 1预测单个实体，GPU运行了一个晚上，比训练时间都慢吗？一直处于Finish build vocabulary
Finish build word dictionary
number of training examples: 250186
model restored
Read test data
Type index from (0 to 29981) to continue:  这个状态
遗憾的是，这里上传不了屏幕截图 ，

**Comment by EagleW** [comment]
This is because you need to input a index to select a instance from dataset as https://github.com/EagleW/Describing_a_Knowledge_Base/blob/246be6f5d97a0ff57fb18700352965223355883d/main.py#L162
You need to customized the code to work for your own input

**Comment by yuanyuan12080317** [comment]
我好愚昧，谢谢您的回复 爱您
