### ISSUE TITLE
problem 3

### ISSUE THREAD

**Issue by yuanyuan12080317** [EagleW/Describing_a_Knowledge_Base#6]
亲爱的楼主，不好意思又麻烦您，我运行python main.py --cuda --mode 3 报错BrokenPipeError: [Errno 32] Broken pipe  从网上找了解决方案都是修改num_workers =0，可是我们没有调用torch.utils.data.DataLoader()函数

**Comment by EagleW** [comment]
Hi can you share more details about the bug? Did you run pytorch 0.4?

**Comment by EagleW** [comment]
Maybe you can copy error text to the issue. Thanks!

**Comment by yuanyuan12080317** [comment]
Finish build vocabulary
Finish build word dictionary
number of training examples: 250186
model restored
Read test data
number of test examples: 29982
Start Evaluating
Traceback (most recent call last):
  File "main.py", line 210, in <module>
    final_scores = eval_f.evaluate(live=True, cand=cand, ref=ref)
  File "/home/zhangluyuan/workspace/two/knowledge_base/Describing_a_Knowledge_Base-zly/eval_final.py", line 66, in evaluate
    final_scores = self.score(ref, hypo)
  File "/home/zhangluyuan/workspace/two/knowledge_base/Describing_a_Knowledge_Base-zly/eval_final.py", line 33, in score
    score, scores = scorer.compute_score(ref, hypo)
  File "/home/zhangluyuan/workspace/two/knowledge_base/Describing_a_Knowledge_Base-zly/pycocoevalcap/meteor/meteor.py", line 40, in compute_score
    self.meteor_p.stdin.write(score_line + '\n')
BrokenPipeError: [Errno 32] Broken pipe

**Comment by EagleW** [comment]
Do you install java on your computer?
The meteor requires a pre-installed java

**Comment by yuanyuan12080317** [comment]
But I use a Linux server

**Comment by EagleW** [comment]
Can you run https://github.com/EagleW/Describing_a_Knowledge_Base/blob/master/eval.py to see whether it works or not?

**Comment by yuanyuan12080317** [comment]
yes 
 Bleu_4:	 82.2267233339004
ROUGE_L: 83.33333333333333

**Comment by yuanyuan12080317** [comment]
But python eval_final.py 
Traceback (most recent call last):
  File "eval_final.py", line 87, in <module>
    x.evaluate(live=True, cand=cand, ref=ref)
  File "eval_final.py", line 66, in evaluate
    final_scores = self.score(ref, hypo)
  File "eval_final.py", line 33, in score
    score, scores = scorer.compute_score(ref, hypo)
  File "/home/zhangluyuan/workspace/two/knowledge_base/Describing_a_Knowledge_Base-zly/pycocoevalcap/meteor/meteor.py", line 40, in compute_score
    self.meteor_p.stdin.write(score_line + '\n')
BrokenPipeError: [Errno 32] Broken pipe

**Comment by EagleW** [comment]
Are you using university server? E.g. UIUC server requires to load java even it is preinstalled

**Comment by yuanyuan12080317** [comment]
yes university server，so，，what need Ido？

**Comment by EagleW** [comment]
For UIUC, you need to run `module load sun-jdk`. You need to check your university's setting

**Comment by yuanyuan12080317** [comment]
If I do not use METEOR ,Do I still need to do this?

**Comment by EagleW** [comment]
You can comment line 16 and line 73 in https://github.com/EagleW/Describing_a_Knowledge_Base/blob/master/eval_final.py

**Comment by EagleW** [comment]
YOu also need to remove meteor in https://github.com/EagleW/Describing_a_Knowledge_Base/blob/246be6f5d97a0ff57fb18700352965223355883d/main.py#L204

**Comment by yuanyuan12080317** [comment]
That's very patient of you. Thank you very much
