### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by yuanyuan12080317** [EagleW/Describing_a_Knowledge_Base#7]
（Why do the main functions cand and ref in the eval_final file have two descriptions generated_description1 and generated_description2?？Do we need two values to compare？？）
为什么eval_final文件的main函数cand和ref里面有两个，分别为generated_description1和generated_description2？需要有两个值对比吗

**Comment by EagleW** [comment]
This is the default examples provided by pycocoeval. Their can be multiple reference for a single generated results since coco dataset has multiple captions for one image.

**Comment by yuanyuan12080317** [comment]
（Your paper mentioned coverage loss, but other parts of the paper did not mention coverage mechanism, but you used this mechanism, right?  ）你的论文提到了coverage loss，但是论文其他部分没有提到覆盖率机制，但是您使用了这个机制是吗？

**Comment by EagleW** [comment]
Yes coverage loss is on https://github.com/EagleW/Describing_a_Knowledge_Base/blob/246be6f5d97a0ff57fb18700352965223355883d/structure_generator/DecoderRNN.py#L142-L145

**Comment by yuanyuan12080317** [comment]
yes ，Does the coverage mechanism eliminate repetition？

**Comment by EagleW** [comment]
It only remove some repetition
